Linebalance/Controllers/linebarlanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Linebalance.Models;
using System.Configuration;
using Oracle.ManagedDataAccess.Client;
using Linebalance.Comfunction;
using System.Data;
using System.Data.SqlClient;
using OfficeOpenXml;
using System.IO;

using HttpException = System.Web.HttpException;
using Microsoft.Win32;
using System.Web.UI;
using System.Xml;
using System.Xml.Serialization;
using System.Text;

namespace Linebalance.Controllers
{
    public class linebarlanceController : Controller
    {
        static List<R_LOGIN> lLogin = new List<R_LOGIN>();
        static List<R_LOGIN_FAC> lLoginF = new List<R_LOGIN_FAC>();
        static List<R_LOGIN_LINE> lLoginL = new List<R_LOGIN_LINE>();
        static List<R_LOGIN_AREA> lLoginA = new List<R_LOGIN_AREA>();
        static List<LineBalance> Data = new List<LineBalance>();
        static List<OIRate> OIrate = new List<OIRate>();
        static List<Input> InputData = new List<Input>();
        static List<T_MODEL> MO = new List<T_MODEL>();
        static List<GLinebalance> GData = new List<GLinebalance>();
        static List<GLinebalance2> GCalL2 = new List<GLinebalance2>();
        static string plantlogin;
        static string GArea;
        public ActionResult GetloginOA()
        {
            lLogin.Clear();
            GData.Clear();
            //Response.Redirect("http://thbpo-oa-service.delta.corp/OADETSingleSignOn/Check.aspx?URL=http://thbpoprodap-mes.delta.corp/Linebalance/linebarlance/Login");           
            Response.Redirect("http://thbpo-oa-service.delta.corp/OADETSingleSignOn/Check.aspx?URL=https://localhost:44334/linebarlance/Login");
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {
            lLogin.Clear();
            GData.Clear();
            string user = Request["userempid"];
            string account = Request["userNTAccount"];

            if (account != null)
            {
                R_LOGIN cus = new R_LOGIN();

                cus.emp_no = user;
                cus.emp_account = account;
                lLogin.Add(cus);

                SqlConnection conns = new SqlConnection("Server=THBPOCIMDB; Database=MESPRDDB; User=MESDB; Password=MES12345");
                System.Data.SqlClient.SqlCommand command = new System.Data.SqlClient.SqlCommand();
                command.CommandType = System.Data.CommandType.Text;

                command.CommandText = "insert into MES_UTILIZE_LOGIN([USER_ID],[USER_NAME],[DATE_LOGIN]) values('" + user + "','" + account + "','" + DateTime.Now + "')";
                command.Connection = conns;

                conns.Open();
                command.ExecuteNonQuery();
                conns.Close();

            }
            else
            {
                return Redirect("GetloginOA");
            }

            ViewBag.User = user;

            return View(lLogin);
        }
        public static void Getdataline()
        {

 
            LineBalance item = new LineBalance();
            item.EQUIPMENT_CODE = "";
            item.LINE_NAME = "";
            item.STATION_NAME = "";
            item.BEGIN_POINT = "";
            item.END_POINT = "";
            item.CYCLE_TIME = "";
            item.INPUT_QTY = "";
            item.PASS_QTY = "";
            item.FAIL_QTY = "";
            item.WARNING_CNT = "";
            item.RUNNING_TIME = "";
            item.WAITING_TIME = "";
            item.MO_NUMBER = "";
            item.MODEL_NAME = "";
            item.BARCODE = "";
            item.P_ID = "";
            Data.Add(item);
        }
        public ActionResult ZeroLineBalance()
        {

            Data.Clear();
            string plant = lLoginF[0].SCHEMA;
            string factory = InputData[0].FACTORY;
            string line = InputData[0].LINE;
            string area = InputData[0].AREAR;
            string model = InputData[0].MODEL;
            string date1 = InputData[0].DATE1;
            string date2 = InputData[0].DATE2;

            #region DET6-7
            if (plant == "DET_FM" || plant == "DET_CNDC")
            {
                using (OracleConnection conn = ConFunc.GetDBConnection6())
                {
                    var _with1 = conn;
                    if (_with1.State == ConnectionState.Open)
                        _with1.Close();
                    _with1.Open();

                    string str = @"select * from (SELECT NVL(M.OI_RATE, 20) RATE, T.Line_Name"+
                                  " from "+plant+".R_SCHEDULE_SFCS_T T "+
                                  "LEFT JOIN "+plant+".R_SCHEDULE_SAP_T M " +
                                  "ON T.SCHL_NO = M.SCHL_NO " +
                                  "where LINE_NAME = ('"+line+"')" +
                                  "and t.SFCS_MODEL = '"+model+"'  " +
                                  "and t.start_date BETWEEN to_date('"+date1+"','YYYYMMDD HH24miss') and to_date('"+date2+"','YYYYMMDD HH24miss')  " +
                                  "ORDER BY T.SCHL_NO) " +
                                  "WHERE ROWNUM = 1";
                    OracleCommand cmd = new OracleCommand(str, conn);
                    OracleDataReader reader;
                    reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {

                        OIRate OI = new OIRate();
                        OI.RATE = reader["RATE"].ToString();
                        OI.LINE_NAME = reader["LINE_NAME"].ToString();

                        OIrate.Add(OI);

                    }
                }

                using (OracleConnection conn = ConFunc.GetDBConnection6())
                {
                    var _with1 = conn;
                    if (_with1.State == ConnectionState.Open)
                        _with1.Close();
                    _with1.Open();

                    string str = @"select b.equipment_code,c.line_name,d.prod_area_desc,c.group_name,c.station_name,c.pqm_name_en,a.begin_point,a.end_point,a.cycle_time,a.input_qty,a.pass_qty,a.fail_qty,a.warning_cnt,a.running_time,a.waiting_time,a.mo_number,a.model_name,a.barcode,a.p_id" +
                                " from " + plant + ".r_equipment_pub_param_record_t a inner join " + plant + ".c_equipment_basic_t b on a.equipment_id = b.equipment_id " +
                                "inner join " + plant + ".c_station_config_t c " +
                                "on a.equipment_id = c.equipment_id " +
                                "inner JOIN " + plant + ".C_PROD_AREA_T d on b.prod_area_id = d.prod_area_id" +
                                " where c.line_name = '" + line + "' and a.model_name = '" + model + "' and d.prod_area_desc ='" + area + "'and a.end_point" +
                                " BETWEEN to_date('" + date1 + "','YYYYMMDD HH24miss') and to_date('" + date2 + "','YYYYMMDD HH24miss') ";
                    OracleCommand cmd = new OracleCommand(str, conn);
                    OracleDataReader reader;
                    reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {

                        LineBalance item = new LineBalance();
                        item.EQUIPMENT_CODE = reader["EQUIPMENT_CODE"].ToString();
                        item.LINE_NAME = reader["LINE_NAME"].ToString();
                        item.GROUP_NAME = reader["GROUP_NAME"].ToString();
                        item.STATION_NAME = reader["STATION_NAME"].ToString();
                        item.BEGIN_POINT = reader["BEGIN_POINT"].ToString();
                        item.END_POINT = reader["END_POINT"].ToString();
                        item.CYCLE_TIME = reader["CYCLE_TIME"].ToString();
                        item.INPUT_QTY = reader["INPUT_QTY"].ToString();
                        item.PASS_QTY = reader["PASS_QTY"].ToString();
                        item.FAIL_QTY = reader["FAIL_QTY"].ToString();
                        item.WARNING_CNT = reader["WARNING_CNT"].ToString();
                        item.RUNNING_TIME = reader["RUNNING_TIME"].ToString();
                        item.WAITING_TIME = reader["WARNING_CNT"].ToString();
                        item.MO_NUMBER = reader["MO_NUMBER"].ToString();
                        item.MODEL_NAME = reader["MODEL_NAME"].ToString();
                        item.BARCODE = reader["BARCODE"].ToString();
                        item.P_ID = reader["P_ID"].ToString();
                        Data.Add(item);

                    }
                }

                        using (OracleConnection conn = ConFunc.GetDBConnection6())
                        {
                            var _with1 = conn;
                            if (_with1.State == ConnectionState.Open)
                                _with1.Close();
                            _with1.Open();

                            string str = @"select ROUND((CYCLETIME/CAL)/group_qty,2) as cal_linebalance,group_name,EQUIPMENT_CODE from (select b.equipment_code as equipment_code ,d.prod_area_desc,a.model_name,sum(a.CYCLE_TIME)as CYCLETIME, COUNT(*)as CAL,c.group_name as group_name, NVL(e.group_qty, 1)as group_qty from " + plant + ".r_equipment_pub_param_record_t a inner join " + plant + ".c_equipment_basic_t b on a.equipment_id = b.equipment_id inner join " + plant + ".c_station_config_t c on a.equipment_id = c.equipment_id inner JOIN " + plant + ".C_PROD_AREA_T d on b.prod_area_id = d.prod_area_id left join " + plant + ".C_MODEL_GROUP_QTY_T e on c.group_name = e.group_name and a.model_name = e.model_name where c.line_name = '" + line + "' and a.model_name = '" + model + "' and d.prod_area_desc = '" + area + "' and a.end_point BETWEEN to_date('" + date1 + "','YYYYMMDD HH24miss') and to_date('" + date2 + "','YYYYMMDD HH24miss') group by b.equipment_code,d.prod_area_desc,c.group_name,a.model_name,e.group_qty)";

Linebalance/Views/linebarlance/BTQry.cshtml
@model IEnumerable<Linebalance.Models.GLinebalance>

@using Linebalance.Models;

@{
    ViewBag.Title = "DASHBORD";
    Layout = null;
    //List<MES_R_UTILIZE> Fre = ViewData["body"] as List<MES_R_UTILIZE>;
    ////List<MES_R_UTILIZE_> ChartLine = ViewData["ChLine"] as List<MES_R_UTILIZE_LINE>;
    ////List<MES>
    //List<Input> factory = ViewData["Fac"] as List<Input>;
    //List<Input> parea = ViewData["PArea"] as List<Input>;
    //List<Input> pplant = ViewData["Plant"] as List<Input>;
    List<OIRate> OI = ViewData["OI"] as List<OIRate>;
    List<Input> facs = ViewData["Fac"] as List<Input>;
    List<R_LOGIN_AREA> aears = ViewData["Area"] as List<R_LOGIN_AREA>;
    List<R_LOGIN_LINE> lines = ViewData["Line"] as List<R_LOGIN_LINE>;
    List<T_MODEL> modelZ = ViewData["Model"] as List<T_MODEL>;
    //List<Qfactory_new> FacBQ = ViewData["FacNew"] as List<Qfactory_new>;
    //ViewBag.User = @ViewBag.User;
    //ViewBag.fac = @ViewBag.fac;
    //List<Input> ldata = ViewData["body"] as List<Input>;
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel='stylesheet' href='~/Css/datedanger.css'>

}


<div id="tableRe">
    <div class="sup-box-right-fix">
        <div class="scroll-pane">
            <table id="datatable">

                <thead>

                    <tr>

                        <th></th>

                        <th>Machine</th>
                        <th>@OI[0].RATE</th>

                    </tr>

                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <th>@item.EQUIPMENT_CODE</th>
                        <td>@item.CYCLETIME</td>

                        <td>@OI[0].RATE</td>
                    </tr>


                    }



                </tbody>

            </table>
        </div>
    </div>
    <div class="sup-box-next highcharts-b highcharts-figure">
        <div id="container" style="width: 100%; height: 420px; margin: 0 auto"></div>
    </div>
</div>
<div class="sup-box-right">
    @*<button class="btnE"><i class="fas fa-file-export" style="font-size: 15px;">@Html.ActionLink("Export", "DownloadFile")</i></button>*@
    <div class="scroll-pane">
        <table id="QueryTable" class="table-fill" overflow:auto;>

            <thead>
                <tr>
                    <th>FACTORY</th>
                    @*<th>Production Plan</th>*@
                    @foreach (var items in Model)
                    {
                        <th id="@items.EQUIPMENT_CODE">@items.EQUIPMENT_CODE</th>
                    }

                </tr>
            </thead>
            <tbody>

                <tr>

                    <td>DET</td>

                    @*<td>@Fre[0].PROD_AREA</td>*@

                    @foreach (var item in Model)
                    {

                        <td @*onclick="gDate(this)"*@>@item.CYCLETIME %</td>

                    }
                </tr>
            </tbody>
        </table>

    </div>
</div>




<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        setTimeout(function () {
            location.reload();
        }, 3000000);

        $('#DateId').daterangepicker(
            {
                "singleDatePicker": true,
                "startDate": moment(),
                "endDate": moment().endOf('year'),
                "opens": "center"
            });

        Highcharts.chart('container', {

            data: {
                table: document.getElementById('datatable')
            },

            series: [{
                type: 'column',
                color: '#00ADD4'
            },
            {
                type: 'line',
                color: '#64D7D7',
                lineWidth: 3


            }],
            plotOptions: {
                line: { // <--- Chart type here, check the API reference first!
                    marker: {
                        enabled: false
                    }
                }
            },

            title: {

                text: 'Line Balance'

            },

            yAxis: {
                min: 0,
                title: {
                    text: ''
                }
            },
            tooltip : {
                mode: 'index',
                callbacks: {
                    labelColor: tooltipItem => {
                        var color = tooltipItem.datasetIndex == 0 ? 'green' : 'red';
                        return {
                            borderColor: color,
                            backgroundColor: color
                        }
                    }
                }

            }

        });


    });

    $(function () {
        $('input[name="daterange"]').daterangepicker({
            opens: 'left'
        }, function (start, end, label) {
            console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        });
    });
    function gDate(x) {

        alert("Row index is: " + x.rowIndex);
    }

    function ajaxSet(url, method, postData) {
        return {
            type: method,
            url: url,
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(postData),
            dataType: "html",
        };
    }

    function LoadInfo() {

        var x = document.getElementById("myCheck").checked;

        $("#id").empty();
        var fac = {};
        fac.factory = $("#factory").val();
        fac.Area = $("#Area").val();
        fac.line = $("#Line").val();
        fac.model = $("#Model").val();
        fac.date = $("#Date").val();
        fac.check = x;

        var Settings = ajaxSet("@Url.Action("ConLineBalance", "linebarlance")", "POST", fac);
        $.ajax(Settings).done(function (resHtml) {
            $('#tableRe').html('');
            $('#tableRe').html(resHtml);


        }).fail(function (res) {
            $('#tableRe').html(res.responseText);
        });


    }
    $("#Query").click(function (e) {

        e.preventDefault()
        LoadInfo();

    });





    //$('#QueryTable tbody').on('click', 'tr', function () {
    //    var data = table.row(this).data();
    //    alert('You clicked on ' + data[0] + '\'s row');
    //});

    //$("#QueryTable tbody td").click(function () {
    //    console.log($(this).text());
    //});

    $("#Export").click(function () {
        var fac = {};
        fac.plant = $("#plant").val();
        fac.factory = $("#factory").val();
        //fac.START = $("#START").val();
        //fac.END = $("#END").val();
        fac.paera = $("#paera").val();
        fac.line = $("#line").val();
        jQuery.ajax({
            type: "POST",
            url: "/Home/BntExport",
            data: JSON.stringify(fac),
            dataType: "json",
            contentType: "application/json",
            traditional: true,
            success: function (data) {
                //alert("ok");
            }
        });
    });

    $("#Reset").click(function () {
        jQuery.ajax({
            type: "POST",
            url: "Utilization/Home/BntReset",
            //data: JSON.stringify(fac),
            dataType: "json",
            contentType: "application/json",
            traditional: true,

        });
    });


</script>

Linebalance/Views/linebarlance/Login.cshtml
@*@model Dashbord_demo.Models.R_LONGIN*@
@model IEnumerable<Linebalance.Models.R_LOGIN>
@using Linebalance.Models;

@{

    ViewBag.Title = "LOGIN";
    //ViewBag.User = @ViewBag.User;


    //List<R_LONGIN> rLogin = ViewData["rLogin1"] as List<R_LONGIN>;
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<style type="text/css">

    .login-form h3 {
        font-size: 20px;
        text-align: center;
        color: #fff;
        margin-bottom: 30px;
        font-weight: normal;
    }

    .login-form h2 {
        font-size: 20px;
        text-align: center;
        color: #0087dc;
        margin-bottom: 30px;
        font-weight: normal;
    }

    .login-form h1 {
        font-size: 36px;
        text-align: center;
        color: #45aba6;
        margin-bottom: 30px;
        font-weight: normal;
    }

    .login-form .social-icon {
        width: 100%;
        font-size: 20px;
        padding-top: 20px;
        color: #fff;
        text-align: center;
        float: left;
        top: 1300px;
    }

    .login-form-heard {
        font-size: 25px;
        text-align: center;
        color: #ccc;
        margin-bottom: 30px;
        font-weight: normal;
        margin-left: 800px;
        margin-right: 300px;
        background: #45aba6;
        width: 400px;
        height: 50px;
        padding: 30px 30px 30px 30px;
        position: absolute;
        top: 150px;
        left: 30px;
        right: 20px;
        bottom: auto;
        border-radius: 20px;
    }

    .login-form {
        margin-left: 810px;
        margin-right: 300px;
        background: #fff;
        /* background-image: url(https://img.freepik.com/free-photo/business-people-meeting-team-working-wooden-desk-hand-man-pointing-financial-documents_2034-1518.jpg);*/
        width: 400px;
        height: 350px;
        padding: 30px 30px 30px 30px;
        position: absolute;
        top: 220px;
        left: 30px;
        right: 20px;
        bottom: auto;
        border-radius: 5px;
    }

    .login-form-big {
        margin-left: 250px;
        margin-right: 100px;
        background: #fff;
        /*background-image: url(https://cdn-icons-png.flaticon.com/512/1055/1055644.png);*/
        width: 1000px;
        height: 550px;
        padding: 30px 30px 30px 30px;
        position: absolute;
        top: 125px;
        left: 30px;
        right: 20px;
        bottom: auto;
        border-radius: 50px;
    }

    .login-form-pic {
        margin-left: 250px;
        margin-right: 100px;
        background: #fff;
        /*background-image: url(https://cdn-icons-png.flaticon.com/512/1055/1055644.png);*/
        /* width: 515px;
        height: 512px;*/
        padding: 30px 30px 30px 30px;
        position: absolute;
        top: 18px;
        left: 10px;
        right: 20px;
        bottom: auto;
        border-radius: 80px;
    }

    #imgback {
        background-image: url(http://thbpoprodap-mes.delta.corp/Utilization/image/quick-reportsa.png);
        /*background-image: url(https://cdn-icons-png.flaticon.com/512/1055/1055644.png);*/
        /*height: 512px;
        display: inline-block;
        width: 515px;*/
        height: 512px;
        display: inline-block;
        width: 515px;
        margin: 0px;
        margin-left: 0;
    }


    .login-form-sup {
        margin-left: 100px;
        margin-right: 300px;
        background: #fff;
        width: 450px;
        height: 400px;
        padding: 30px 30px 30px 30px;
        position: absolute;
        top: 170px;
        /*        left: 0px;
        right: 0px;*/
        bottom: auto;
        border-radius: 5px;
    }

    .form-group {
        float: left;
        width: 100%;
        margin: 0 0 15px;
        position: relative;
    }

    .login-form input {
        width: 100%;
        padding: 5px;
        height: 56px;
        border-radius: 74px;
        /*border: 1px solid #ccc;*/
        box-sizing: border-box;
        font-size: 20px;
        padding-left: 75px;
        font-family: Courier New;
        border: 1px solid #c3c1c1;
    }

    .login-form .form-group .input-icon {
        font-size: 15px;
        display: -webkit-box;
        display: -webkit-flex;
        display: -moz-box;
        display: -ms-flexbox;
        display: flex;
        align-items: center;
        position: absolute;
        border-radius: 25px;
        bottom: 0;
        height: 100%;
        padding-left: 35px;
        color: #666;
    }

    .login-form .login-btn {
        /*background: #45aba6;*/
        background-image: linear-gradient(to bottom right, #00afef, #00afef, #00afef);
        padding: 11px 50px;
        /*border-color: linear-gradient(to bottom right, #03ccfa, #3fc4bd, rgb(0 255 255));*/
        color: #fff;
        text-align: center;
        margin: 0 auto;
        font-size: 20px;
        border: 1px solid #00afef;
        border-radius: 44px;
        width: 100%;
        height: 56px;
        cursor: pointer;
    }

    .login-form .reset-psw {
        float: left;
        width: 100%;
        text-decoration: none;
        color: #45aba6;
        font-size: 14px;
        text-align: center;
        margin-top: 11px;
    }

    .login-form .social-icon button {
        font-size: 20px;
        color: white;
        height: 50px;
        width: 50px;
        background: #45aba6;
        border-radius: 60%;
        margin: 0px 10px;
        border: none;
        cursor: pointer;
    }

    .login-form button:hover {
        opacity: 0.9;
    }

    .login-form .seperator {
        float: left;
        width: 100%;
        border-top: 1px solid #ccc;
        /*border: 1px solid #00afef;*/
        text-align: center;
        margin: 50px 0 0;
    }

        .login-form .seperator b {
            width: 40px;
            height: 40px;
            font-size: 16px;
            text-align: center;
            line-height: 40px;
            background: #fff;
            display: inline-block;
            border: 1px solid #e0e0e0;
            border-radius: 50%;
            position: relative;
            top: -22px;
            z-index: 1;
        }

    .login-form p {
        float: left;
        width: 100%;
        text-align: center;
        font-size: 16px;
        margin: 0 0 10px;
    }

    .form-input {
        position: relative;
        font-family: "Source Sans Pro", sans-serif;
        /*font-weight: 600;*/
        width: 100%;
        height: 53px;
        /*left: 10px;*/
        /*right: px;*/
        border: none;
        padding: 0 15px;
        /*padding-left: 10px;*/
        margin-right: 75px;
        box-shadow: none;
        outline: none;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        -ms-transition: all .5s ease;
        -o-transition: all .5s ease;
        transition: all .5s ease;
    }


        .form-input.smooth-corner {
            border-radius: 90px;
            padding-left: 75px;
            font-family: Courier New;
            font-size: 20px;
        }

        .form-input.basic {
            border: 2px solid rgba(0, 0, 0, .15);
        }

            .form-input.basic:hover {
                border-color: rgba(0, 0, 0, .35);
                box-shadow: 0 0 5px rgba(0, 0, 0, .2);
            }

            .form-input.basic:focus {
                border-color: #4285F4;
                box-shadow: 0 0 10px rgba(66, 133, 244, .5);
            }
</style>
<body>
    <div id="LoginC">
        <div class="login-form-big">
            <div class="login-form-pic" id="imgback">
                @*<h3>Login</h3>*@
            </div>
        </div>

        <div class="login-form">

            <form action="~/linebarlance/LineBanace" method="post" target="_blank">
                <h2>Login From</h2>
                @if (Model != null)
                {
                    foreach (var ac in Model)
                    {
                        <div class="form-group">

                            <input class="form-input basic smooth-corner" id="user" type="text" name="user" value="@ac.emp_account">
                            <span class="input-icon"><i class="fas fa-user-check"></i></span>

                        </div>
                    }
                }
                <div class="form-group">
                    <select id="plant" onselect="slplant" name="plant" class="combobox form-input basic smooth-corner">
                        <option></option>
                        <option id="0">DET_AM</option>
                        <option id="1">DET_CN</option>
                        <option id="2">DET_DA</option>
                        <option id="3">DET_MP</option>
                        <option id="4">DET_PS</option>
                        <option id="5">DET_HP</option>
                        <option id="6">SFISM4</option>
                        <option id="7">DET_FM</option>
                        <option id="8">DET_MS</option>
                        <option id="9">DET_CNDC</option>
                    </select>
                    <span class="input-icon"><i class="fas fa-landmark"></i></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="login-btn">
                        <a href="~/linebarlance/LineBanace">
                            <h3>Login</h3>
                        </a>
                    @*</input>*@
                </div>
            </form>
        </div>
    </div>
</body>

<script type="text/javascript">

    $(document).ready(function () {
        setTimeout(function () {
            location.reload();
        }, 30000);


    });
     function Load() {
        var fac = {};
        fac.plant = $("#plant").val();

        var Settings = ajaxSet("@Url.Action("LineBanace", "linebarlance")", "POST", fac);
        $.ajax(Settings).done(function (resHtml) {
            $('#LoginC').html('');
            $('#LoginC').html(resHtml);


        }).fail(function (res) {
            $('#LoginC').html(res.responseText);
        });


    }
    //$("#loadc").click(function (e) {

    //    Load();

    //});
</script>